# Julia Connelly
# 605.614 System Development in the UNIX Environment
# Makefile
# Builds all project libraries. Supports targets it, install, clean, depend.

PROJECT_DIR = ../../
include $(PROJECT_DIR)/common.mk

it:
	$(MAKE_IT)

install:
	$(MAKE_INSTALL)

clean:
	$(MAKE_CLEAN)

depend:
	$(MAKE_DEPEND)
